---
title: "viz_class_3"
author: "Caleigh Dwyer"
date: "2023-10-05"
output: github_document
---

Exploratory analysis (EDA)!

```{r set up}
library(tidyverse)
library(ggridges)
library(lubridate)

```

```{r}
weather_df <- 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2023-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
  
```

^chunk didn't work for me

##initial numeric work

```{r}
weather_df |> 
  ggplot(aes(x=prcp)) +
  geom_histogram()

```

here are the big outliers:

```{r}
weather_df |> 
  filter(prcp > 1000)
```


```{r}
weather_df |> 
  filter(tmax>= 20, tmax <= 30) |> 
  ggplot(aes(x=tmin, y= tmax, color = name)) +
  geom_point()

```

##grouping

```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(n_obs = n())
```

```{r}
weather_df |> 
  count(name, name = "n_obs")
```

```{r}

weather_df |> 
  count(name, month) |> 
  pivot_wider(
    names_from = name,
    values_from = n
  )
```


##general summaries

```{r}
weather_df |> 
  group_by (name) |> 
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax, na.rm = TRUE),
    median_tmax = median (tmax, na.rm = TRUE)
  ##take averages after removing missing values
  )
```


```{r}
weather_df |> 
  group_by(name, month) |> 
  summarize(mean_tmax = mean(tmax, na.rm = TRUE)) |> 
  ggplot(aes(x=month, y=mean_tmax, color = name)) + 
  geom_point()+
  geom_line()
```


```{r}
weather_df |> 
  group_by(name,month) |> 
  summarize(mean_tmax = mean(tmax, na.rm = TRUE)) |> 
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  ) |> 
  knitr::kable(digits=2)
##knitr function displays a more organized table in the knit document
  
```

##grouped mutate

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(mean_tmax = mean(tmax, na.rm= TRUE)) |> view()
```


```{r}
weather_df |> 
  group_by(name) |> 
  mutate(
    mean_tmax = mean(tmax, na.rm= TRUE),
    centered_tmax = tmax-mean_tmax) |> 
  ggplot(aes(x=date, y=centered_tmax, color=name))+
  geom_point()
 
```

window functions, helpful for ranking things (e.g. findnig the coldest day)

```{r}
weather_df |> 
  group_by(name, month) |> 
  mutate(tmax_rank = min_rank(desc(tmax))) |> 
  filter(tmax_rank <2)

##this shows the hottest day per month
```


lags

```{r}
weather_df |> 
  group_by(name) |> 
  mutate(yesterday_tmax = lag(tmax))

##this shows yesterday's weather in same row as today's weather so you can compare.
##if you don't specify grouping, the lag will just choose whatever is three rows back.
```


```{r}
weather_df |> 
  group_by(name) |> 
  mutate(temp_change = tmax - lag(tmax)) |> 
  summarize(
    sd_temp_change = sd(temp_change, na.rm = TRUE)
  )

## this will show you the temperature change between yesterday and today, then you can show the variation in temp change using sd
```

